version: '3'

services:
  web:
    image: takaruma7/miw:latest
    restart: always
    ports:
      - "80:80"
    environment:
      DB_HOST: ${MYSQL_HOST}
      DB_PORT: ${MYSQL_PORT}
      DB_NAME: ${MYSQL_DATABASE}
      DB_USER: ${MYSQL_USER}
      DB_PASS: ${MYSQL_PASSWORD}
      APP_ENV: production
      SMTP_HOST: ${SMTP_HOST}
      SMTP_USERNAME: ${SMTP_USERNAME}
      SMTP_PASSWORD: ${SMTP_PASSWORD}
      SMTP_PORT: ${SMTP_PORT:-587}
      SMTP_ENCRYPTION: ${SMTP_ENCRYPTION:-tls}
    volumes:
      - uploads_data:/var/www/html/uploads
      - documents_data:/var/www/html/documents
      - logs_data:/var/www/html/logs

volumes:
  uploads_data:
  documents_data:
  logs_data:
