services:
  web:
    build: .
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
      - ./uploads:/var/www/html/uploads
      - ./documents:/var/www/html/documents
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: data_miw
      DB_USER: miw_user
      DB_PASS: miw_password
      APP_ENV: development
      SMTP_HOST: ${SMTP_HOST:-smtp.gmail.com}
      SMTP_USERNAME: ${SMTP_USERNAME:-your-email@gmail.com}
      SMTP_PASSWORD: ${SMTP_PASSWORD:-your-app-password}
      SMTP_PORT: ${SMTP_PORT:-587}
      SMTP_ENCRYPTION: ${SMTP_ENCRYPTION:-tls}
    networks:
      - miw-network

  db:
    image: mysql:8.0
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: data_miw
      MYSQL_USER: miw_user
      MYSQL_PASSWORD: miw_password
      MYSQL_ROOT_PASSWORD: root_password
    volumes:
      - mysql_data:/var/lib/mysql
      - ./backup_sql:/docker-entrypoint-initdb.d
    networks:
      - miw-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      PMA_USER: miw_user
      PMA_PASSWORD: miw_password
    depends_on:
      - db
    networks:
      - miw-network

volumes:
  mysql_data:

networks:
  miw-network:
