services:
  # Web Service using Docker
  - type: web
    name: miw-web
    env: docker
    region: singapore
    plan: free
    branch: main
    healthCheckPath: /
    buildCommand: docker build -t miw-app .
    startCommand: apache2-foreground
    envVars:
      - key: APP_ENV
        value: production
      - key: DB_HOST
        fromDatabase:
          name: miw-database
          property: host
      - key: DB_PORT
        fromDatabase:
          name: miw-database
          property: port
      - key: DB_NAME
        fromDatabase:
          name: miw-database
          property: database
      - key: DB_USER
        fromDatabase:
          name: miw-database
          property: user
      - key: DB_PASS
        fromDatabase:
          name: miw-database
          property: password
      - key: SMTP_HOST
        value: smtp.gmail.com
      - key: SMTP_USERNAME
        value: drakestates@gmail.com
      - key: SMTP_PASSWORD
        value: lqqj vnug vrau dkfa
      - key: SMTP_PORT
        value: "587"
      - key: SMTP_ENCRYPTION
        value: tls
      - key: MAX_FILE_SIZE
        value: 10M
      - key: MAX_EXECUTION_TIME
        value: "300"
      - key: SECURE_HEADERS
        value: "true"

databases:
  - name: miw-database
    databaseName: data_miw
    user: miw_user
    plan: free
